services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db_trad
    volumes:
      - ./bdd:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: traducteur
      MYSQL_USER: traducteur
      MYSQL_PASSWORD: traducteur

  adminer:
    image: adminer
    restart: always
    ports:
      - 8087:8080

volumes:
  db_data:
